# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0f5b3276b6905c88f7251d1d953027e138841e30534d2454b3ae229d8d3c26d83dae77b1e0aefde4287e11c680c0f6a0e11f893008dfa0e748dfff255ae8fe7

test:
  secret_key_base: c3adc5999e97c7876b7f97dc6e72968286faeb19b2a1dc27070124a91030447275019bffcd48730ed013ddf8666d4f60550b1fffd333f11cc5e56b98d18cbda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
